version: '3.7'

services:
  adservice:
    image: adservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:9555"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - PORT=9555
  emailservice:
    image: emailservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:8080"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - PORT=8080
      - ENABLE_PROFILER=0
  paymentservice:
    image: paymentservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - PORT=50051
  shippingservice:
    image: shippingservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - PORT=50051
  checkoutservice:
    image: checkoutservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:5050"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
  cartservice:
    image: cartservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:7070"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - REDIS_ADDR=redis-cart:6379
      - PORT=7070
      - LISTEN_ADDR=0.0.0.0
  redis-cart:
    image: redis:alpine #persistance is not yet enabled
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "redis-cli", "keys", "*"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
  currencyservice:
    image: currencyservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:7000"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - PORT=7000
  productcatalogservice:
    image: productcatalogservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:3550"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - PORT=3550
  frontend:
    image: frontend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/_healthz"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
  recommendationservice:
    image: recommendationservice
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:8080"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - ENABLE_PROFILER=0
  loadgenerator:
    image: loadgenerator
    environment:
    - FRONTEND_ADDR=frontend:80
    - USERS=20

